# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  rspec-job:
    # This workflow contains a single job called "build"
    runs-on: ubuntu-latest
    container:
      image: docker://docker.pkg.github.com/wadus16/jenkins/test:1.0
    steps:
        - uses: actions/checkout@v2
        - name: Start database
          run: echo "Hello"
